"""Tax form annotation specification model package."""

from .conditions import ConditionEvaluationError, evaluate_condition
from .formatter import FormatError, format_value
from .models import (
    Annotation,
    AnnotationDocument,
    BoundingBox,
    Condition,
    ConditionOperator,
    CoordinateOrigin,
    CoordinateSystem,
    CoordinateUnit,
    Defaults,
    Format,
    FormatType,
    FormInfo,
    JSONPATH_REGEX,
    Style,
    TextAlignment,
)
from .pipeline import render_document
from .processor import (
    MissingFormatSpecificationError,
    MissingRequiredSourceError,
    ProcessedField,
    ProcessorError,
    ProcessResult,
    process_annotation,
)
from .renderer import (
    ALIGNMENT_MAP,
    DEFAULT_FONT_SIZE,
    RendererError,
    render_fields,
)
from .resolver import (
    IndexOutOfBoundsError,
    InvalidPathSyntaxError,
    MissingPropertyError,
    PathResolutionError,
    ResolverError,
    TypeMismatchError,
    resolve,
)

__all__ = [
    "Annotation",
    "AnnotationDocument",
    "BoundingBox",
    "Condition",
    "ConditionOperator",
    "CoordinateOrigin",
    "CoordinateSystem",
    "CoordinateUnit",
    "Defaults",
    "Format",
    "FormatType",
    "FormInfo",
    "JSONPATH_REGEX",
    "Style",
    "TextAlignment",
    "ResolverError",
    "InvalidPathSyntaxError",
    "PathResolutionError",
    "MissingPropertyError",
    "IndexOutOfBoundsError",
    "TypeMismatchError",
    "resolve",
    "ConditionEvaluationError",
    "evaluate_condition",
    "FormatError",
    "format_value",
    "ProcessorError",
    "MissingRequiredSourceError",
    "MissingFormatSpecificationError",
    "ProcessedField",
    "ProcessResult",
    "process_annotation",
    "ALIGNMENT_MAP",
    "DEFAULT_FONT_SIZE",
    "RendererError",
    "render_fields",
    "render_document",
]